name: SentinelVPN
description: Flutter Android VPN based on OpenVPN Library.
publish_to: 'none'

# App Version
version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

# App dependencies
dependencies:
  flutter:
    sdk: flutter

  flutter_launcher_icons: "^0.13.1"
  #  for lottie animation
  lottie: ^1.1.0
  cupertino_icons:
  hexcolor: ^3.0.1
  #  for calling APIs
  http:
  # for converting csv data to list
  csv: ^5.0.2
  # for storing data in local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0



  get: ^4.6.5

  google_fonts: ^4.0.4


#flutter_icons:
#  android: "ic_launcher"
#  image_path: "assets/icons/icon.png"
#  min_sdk_android: 21
#

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Change package name  
  change_app_package_name: ^1.1.0

flutter:
  # Enabling material design
  uses-material-design: true

  # App assets
  assets:
    - assets/
    - assets/vpn/
    - assets/icons/
    - assets/animations/
    - assets/flags/